### ISSUE TITLE
Beta schedule ? can use now ?

### ISSUE THREAD

**Issue by hervejegou** [SocketCluster/asyngular-server#1]
This looks like a great upgrade to SocketCluster!

We are just moving to SocketCluster server now (testing with  your baasil CLI)  for a small pilot/beta with a few 000 users. We would like to use this new version asap.

When is it realistic to switch to Asyngular-server ? using SocketCluster clients for now ? we need js and Android clients and Asyngular-client is only available for js now.

Would you have a timeframe for beta release for server and for new beta clients ? Thanks.

**Comment by jondubois** [comment]
@hervejegou If you need to support native SC Android clients, then you can start using `asyngular-server` on the back end (make sure that you run it in compatibility mode as the README indicates) but you may want to stick to SocketCluster clients (for now); including the JS `socketcluster-client`.

In compatibility mode, there is a small protocol difference related to socket heartbeat/ping/pong. Hopefully, all major SocketCluster clients will be upgraded to support both old and new ping/pong mechanisms; that would allow us to eventually remove support for compatibility mode completely. The goal is to have both Asyngular and SC always 100% protocol-compatible (both using the new ping/pong mechanism).

Right now `asyngular-client` does not support the old ping/pong mechanism but I might add a 'protocolVersion' option soon on the client as well to enable it - That should make the transition between SC and Asyngular even smoother; then you could mix and match native SC clients with new `asyngular-client` without any issues.

**Comment by hervejegou** [comment]
@jondubois thanks. we will test use ```asyngular-server``` in compatibility mode starting next week. with ```socketcluster-client``` for js and for Android/java.

Once ```asyngular-client``` supports the compatibility mode, we will switch our js client to ```asyngular-client```

**Comment by jondubois** [comment]
@hervejegou I've added a new optional `protocolVersion` field to the JavaScript `asyngular-client`. It defaults to `2` but if you want to be compatible with the current SocketCluster protocol, you should set it to `1` (e.g. `let socket = asyngularClient.create({protocolVersion: 1})`). Note that the `protocolVersion` also needs to be set to `1` when creating the server.

The only protocol difference is the ping/pong which was simplified in v2. We will try to upgrade existing native SocketCluster clients to move to version 2 of the protocol as well since it's a very minor change.

**Comment by hervejegou** [comment]
@jondubois OK this is great news ! so to reconfirm:

We are using ```asyngular-server``` with:
```let agOptions = { protocolVersion: 1, path: '/socketcluster/' };```

We are using ```asyngular-client``` for web client with
```let socket = asyngularClient.create({protocolVersion: 1}))```
And this client can then use the async features and new API for ```asyngular-client ```.

Our Android client can use [socketcluster-client-java](https://github.com/sacOO7/socketcluster-client-java).

Will test this weekend and feedback if any issues.

Once ```socketcluster-client-java``` is upgraded to protocol version 2, we can then switch ```asyngular-server to standard/default protocol version 2.
