### ISSUE TITLE
GKE ingress in default deployment very slow ? can we deploy without ?

### ISSUE THREAD

**Issue by hervejegou** [SocketCluster/asyngular-server#2]
We are testing asyngular server as per docs and it works great. We deployed on GCP as per guides for deployment on Kubernetes:
https://asyngular.io/docs/deploying-to-kubernetes/

and the services works with all services running smoothly. _note: the only headache was the TLS certificate configuration, as mentioned_

However we are seeing latency of more than 300 ms so after investigation it turns out that the GKE ingress service from Google is very slow:

This is deployed in asia-southeast1 (Singapore). I did some ping test on the master GKE controller and the ingress service public IP. The difference is about 200ms delay due to use of ingress load balancer as opposed to connecting straight to a server/service (which is on the master replica). See below screenshots...

Is there a way to deploy asyngular default configuration without the ingress service ? or maybe with a dedicated LB (nginx) instead ? Some googling shows that Google ingress service has latency issues and that using a dedicated LB solves these issues ?

It is a real problem and it defeats the whole purpose of using asyngular. I see process time for messages in the order of 5 ms but the latency introduced by the ingress service is 200 ms ?

Any recommendation would be appreciated.

## Master controller:
<img width="458" alt="Screen Shot 2019-03-20 at 12 43 52 AM" src="https://user-images.githubusercontent.com/771611/54624947-50616780-4aa9-11e9-9898-0a16ee479404.png">

## ingress public IP:
<img width="770" alt="Screen Shot 2019-03-20 at 12 44 15 AM" src="https://user-images.githubusercontent.com/771611/54624962-548d8500-4aa9-11e9-9ddc-521eefb5debb.png">

## Results:
On the left is latency to the Cluster master controller and on the right to the ingress public IP
<img width="1552" alt="Screen Shot 2019-03-20 at 12 45 38 AM" src="https://user-images.githubusercontent.com/771611/54625120-9f0f0180-4aa9-11e9-913d-948f75409614.png">

**Comment by jondubois** [comment]
@hervejegou Thanks for this detailed report. I did notice the following issues when deploying to GKE:

- It took a relatively long time (maybe 4 to 10 minutes) for the ingress to start working after the initial deployment (subsequent deployments were fast though).
- By default, the GKE ingress has a very short connection timeout which kills the WebSocket connection after only 30 seconds (but the timeout can be configured through the control panel; I typically set it to 1 day; `86400` seconds). Obviously this is not a good default for Asyngular.

I didn't check for this issue related to latency so thanks for pointing it out. It does seem like there is something wrong with GKE's default ingress.

I've found that the latest version of Rancher installed on plain Amazon EC2 instances was the smoothest experience.

I think it would be worthwhile to come up with a solution which works perfectly on GKE out of the box. I was considering to use https://github.com/kubernetes/ingress-nginx instead of ingress (it was pretty easy to make it work on Digital Ocean last time I tried) - Maybe the `asyngular` CLI could expose an option to allow us to choose between the default platform ingress or the `nginx` service?

This shouldn't be too difficult to implement. If you have some time to make it work with nginx, feel free to make a PR or let me know what needs to be done. Otherwise I will try to make some time in the next few weeks to get it working.

**Comment by hervejegou** [comment]
@jondubois yes, in fact I tried to look at ```kubernetes ingress-nginx``` when googling the problem and https://github.com/kubernetes/ingress-nginx would be the easiest solution.

One of the thing that works really well out of the box is the asyngular CLI. In fact earlier we were looking at your baasil CLI for same reason. It really simplifies the work of developing and deploying  (a bit like Meteor Galaxy). And GKE seems to work quite well has good web control panels and logs out of the box. So this is a really good solution for developers and for pilot projects.

I do have time but I am a newbie at Kubernetes so modifying your CLI is way above my skillset at this time. The most I can do is try to farm this out to someone more qualified on Upwork?

Could you maybe give me a description of how to modify the asyngular CLI ? and the kubernetes yaml configurations files ? so that it uses the ```kubernetes ingress-nginx```. I will be happy to ask someone more experienced to get it done and submit a PR ?

One other alternative would be to get someone on Upwork to build a Terraform script for deployment of cluster with worker, state, broker, and nginx load balancer on GKE. Terraform scripts are easy to run and can generate docker image, and update the installation. They use a set or variables so anyone could easily modify the script with their variables. We could have two scripts, one to deploy and one to update only the worker (similar asyngular CLI to deploy-update). Do you think that could be a viable option ?

We will continue our development with current setup but our purpose was to replace a mix of Pusher.js and node js server since Pusher.js has latency in the 200-300ms range. So we are clearly hoping that with asyngular running on GKE in our region, we should see latencies in the 30-60ms range if we solve this load balancer delay.

## UPDATE on GKE ingress
I find today that GKE ingress is in fact unstable, not necessarily slower all the time ! really a bit scary. But that also means that the problem may not be only the ingress. In any case we are happy to try with ```kubernetes ingress-nginx``` via your CLI or via terraform scripts ?

![Screen Shot 2019-03-20 at 2 33 13 PM](https://user-images.githubusercontent.com/771611/54663714-32cde580-4b1d-11e9-8314-908bde935071.png)

**Comment by jondubois** [comment]
@hervejegou The `asyngular deploy` command creates all the resources from the .yaml files that are inside your app's `kubernetes/` directory. So you can add additoinal .yaml files if you want to run other services alongside your Asyngular cluster. It could be as simple as just copy pasting the .yaml files provided here (under `GCE - GKE`) https://kubernetes.github.io/ingress-nginx/deploy/

I will try it out when I have some time.

**Comment by hervejegou** [comment]
@hervejegou thanks a lot. things are working out really well so far with asyngular server. But the latency is still going wild (200 ms extra latency due to ingress). I will try to test nginx load balancer next week.

**Comment by jondubois** [comment]
@hervejegou To use `nginx` as the ingress on GKE, you just need to run a few additional commands.

I added a GKE section to the website here which explains: https://asyngular.io/docs/deploying-to-kubernetes/#google-kubernetes-engine-gke

I didn't check the latency though but I suppose that this setup should make things more configurable. To minimize latency, you should make sure that the nginx instance(s) is/are running in the same zone as `agc-worker` and `agc-broker` services.

**Comment by hervejegou** [comment]
@jondubois We are deploying for beta release and I have monitored for last 2 weeks and in fact ingress was unstable for a while but it seems OK now. I see a maximum of 10ms extra latency when pinging the ingress vs pinging the worker container directly. So this is quite acceptable for  a load balancer.

We can close this issue I think. Thanks for your help.

**Comment by mr-bjerre** [comment]
I'm seeing a really slow GKE ingress now - up to 1 second even. Especially if multiple requests are coming in at the same time.
