### ISSUE TITLE
4 errors logged in console for each Socket hung up 

### ISSUE THREAD

**Issue by hervejegou** [SocketCluster/asyngular-server#4]
We use asyngular for new project with GCP and our server is very stable and works great in GCP. not a single crash/restart running for 10 days!

We use GCP console logs to monitor API and socket events and catch our development errors.

We see quite a few Socket hung up errors on server. Each time, it seems to log 4 error messages in the GCP server container log ??

<img width="1135" alt="Screen Shot 2019-05-01 at 3 55 25 PM" src="https://user-images.githubusercontent.com/771611/57009543-c53bcb80-6c29-11e9-949f-6884d8dfea90.png">

Is this a GCP log problem?

This is a very minor issue but it would be slightly more convenient if it logged one error message for socket hung up in GPC console ? socket hung up is a low severity error and seems quite common with clients...

**Comment by jondubois** [comment]
@hervejegou Yes socket hung up is common and just means that the client left abruptly (e.g. app on mobile device closed suddenly, browser left the page without explicitly closing the socket, ...).

I think that GCP expects each JSON error to use up only a single line.

Logging over multiple lines is good for development but not good for production.
You could change the way the error is logged in `server.js` to achieve this. You can check the `ENVIRONMENT` constant and if it's `'prod`` then you can log the error on a single line.

This should also be modified in the Asyngular boilerplate. https://github.com/SocketCluster/asyngular/blob/6caeebfc8fbc352caec0fbff8803c8a20f82676a/app/server.js#L120

**Comment by hervejegou** [comment]
@jondubois thanks will use 'prod'  in ENVIRONMENT or in server.js config section.
