### ISSUE TITLE
socket timeout problems...

### ISSUE THREAD

**Issue by hervejegou** [SocketCluster/asyngular-server#5]
Hi Jonathan: We are using ```asyngular-server``` with socketCluster Android and js clients

We get a lot of socket timeout errors on server and I am not sure how to handle it:
```
{ SocketProtocolError: Did not receive #handshake from client before timeout at AGServerSocket._onClose (/usr/src/app/node_modules/asyngular-server/serversocket.js:956:17) at AGServerSocket.disconnect (/usr/src/app/node_modules/asyngular-server/serversocket.js:971:10) at AGServerSocket._handleHandshakeTimeout (/usr/src/app/node_modules/asyngular-server/serversocket.js:350:8) at Timeout.AGServerSocket._handshakeTimeoutRef.setTimeout (/usr/src/app/node_modules/asyngular-server/serversocket.js:120:10) at ontimeout (timers.js:436:11) at tryOnTimeout (timers.js:300:5) at listOnTimeout (timers.js:263:5) at Timer.processTimers (timers.js:223:10)
```

## Client
We use protocol version 1 and the default socketCluster clients (Android and js).

- How do I prevent this timeout error? is it a problem ?
- I do not see where the socket timeout interval is setup right now in server.js when we deploy 
to Kubernetes ?
- and it seems maybe Android socketCluster client does not send pings by default ? we need to set it ?
- in socketCluster js client, it seems by default it sends pings every 8 to 10 seconds ? I see ```#1``` and ```#2``` in chrome console in the messages for socket connection ? is there a settings for that? _see below_

## Screenshot

<img width="1064" alt="Screen Shot 2019-07-12 at 4 13 49 PM" src="https://user-images.githubusercontent.com/771611/61113138-11c04480-a4c0-11e9-9da1-36328722c1ec.png">

<img width="858" alt="Screen Shot 2019-07-12 at 4 12 16 PM" src="https://user-images.githubusercontent.com/771611/61113060-de7db580-a4bf-11e9-86f6-d87b858dae0f.png">

**Comment by jondubois** [comment]
@hervejegou There is no need to set the pingTimeout on the client side. You just set it on the server side and the client will use that same timeout. See https://asyngular.io/docs/api-ag-server/

The error you've posted can happen if the client is taking a long time to perform the handshake during the connections phase. It's not usually related to ping/pong (heartbeat) timeout (that seems to be working fine).

Is your socket subscribed to a lot of channels? Maybe it's trying to resubscribe to them all at once?
Or maybe you have a handshake middleware on the server which is holding up the connection for too long?

Or maybe your `handshakeTimeout` is too long? You can pass it as an option when attaching/creating the server. Default is 10000 (10 seconds).

**Comment by hervejegou** [comment]
@jondubois  Thank you.. I will experiment with handshakeTimeout and check on the android client if we have some delays during connection phase.
