### ISSUE TITLE
agServer.exchange.subscribe(channel) does not receive channel messages sent by other AG Servers on that channel

### ISSUE THREAD

**Issue by sreplans** [SocketCluster/asyngular-server#6]
I am running agc and while publishing into global channels works fine for clients in the sense that all ag clients connected to all servers in the cluster get the messages published ok, if a server instance does agServer.exchange.transmitPublish('channel', somedata) , only THAT server gets the message on that channel, even though the other servers in the cluster are also doing agServer.exchange.subscribe(channel).   The use case for this is for AG server to AG server communication on pub/sub channels.

**Comment by sreplans** [comment]
I am running agc and while publishing into global channels works fine for clients in the sense that all ag clients connected to all servers in the cluster get the messages published ok, if a server instance does agServer.exchange.transmitPublish('channel', somedata) , only THAT server gets the message on that channel, even though the other servers in the cluster are also doing agServer.exchange.subscribe(channel)...

**Comment by jondubois** [comment]
Thanks for the report, I will try to look into this soon.

**Comment by sreplans** [comment]
Glad to help if you tell me where to look :)

**Comment by jondubois** [comment]
@sreplans Before I start digging into this, can you double check that you are running both agc-broker and agc-state and that the logs on agc-state detect all the brokers. Also, you can try running all the instances on your localhost just to double check that it's not some weird network issue. That would save me some time.

**Comment by sreplans** [comment]
Hi @jondubois yes, I do verify the above, and yes trying in localhost .  I posted more info on gitter.im, and apparently, there was another developer who reported the same issue a while back.  I am running 1 ag-state, one ag-broker, and 2 separate ag-workers on different ports.  The clients do get all messages , irregardless of which server they connect to. 
`The agc-state instance is listening on port 7777
The agc-broker instance 10762208-6766-452a-afc8-a756334959b1 at address ::ffff:127.0.0.1 on port 8888 joined the cluster on socket KHx3HiV8SbtrV7MrAAAA
State server is now allowing agc-worker instances to join the cluster
The agc-worker instance af3439cf-dc9f-4e52-9463-2c43321fdac4 at address ::ffff:127.0.0.1 joined the cluster on socket kgiRsb9LvsnYdPopAAAB
The agc-worker instance cb0288ce-59d9-4bef-b624-2cdf4124b235 at address ::ffff:127.0.0.1 joined the cluster on socket EKG-WHSDiPxLwYn1AAAC
`

**Comment by jondubois** [comment]
@sreplans I was able to reproduce the issue and it should now be fixed in `asyngular@6.1.1` (`asyngular-server@6.2.1`). The new `6.1.1` image was also published on Docker Hub. Please close this issue if it has been resolved for you.

**Comment by sreplans** [comment]
@jondubois Excellent works as advertised now ! thanks!
